### ISSUE TITLE
Status of order does not change 

### ISSUE THREAD

**Issue by virus-zip** [orionprotocol/trading-sdk#14]
The order status will stay on ACCEPTED wether the trade has been filled or not. There is not differentiation between states.

**Comment by eugene-mac** [comment]
> The order status will stay on ACCEPTED wether the trade has been filled or not. There is not differentiation between states.

@virus-zip This happens if the price of the token differs from the price in the order book. The order is accepted for processing and waits for the corresponding price to be executed or canceled if the time is exceeded.
