### ISSUE TITLE
Smaller Slippage <0.5%

### ISSUE THREAD

**Issue by virus-zip** [orionprotocol/trading-sdk#22]
There is no possibility to set the slippage below 0.5% - The possibility to create orders without any slippage would be helpful.

**Comment by eugene-mac** [comment]
> There is no possibility to set the slippage below 0.5% - The possibility to create orders without any slippage would be helpful.

@virus-zip Does this problem still exist? Currently slippage is in range from 0 to 50 percents, but can't be zero.
