### ISSUE TITLE
Orders trough Orion exchange will always cancel 

### ISSUE THREAD

**Issue by virus-zip** [orionprotocol/trading-sdk#27]
Sell orders for ORN will always get partially cancelled. A very small amount of the transaction will always be routed trough Orion and then gets cancelled.

**Comment by eugene-mac** [comment]
> Sell orders for ORN will always get partially cancelled. A very small amount of the transaction will always be routed trough Orion and then gets cancelled.

@virus-zip could you please send some examples of orders and information about the chain used.

**Comment by virus-zip** [comment]
This seems like it is connected to the issue of how the sdk takes USDC amounts. The amount that is not part of the integer will get cancelled. Could that be the case? 

Example: Order for 10.50USDC will succeed with 10USDC traded and 0.50USDC cancelled.

**Comment by virus-zip** [comment]
Also all other orders that are marked as being routed trough Orion will be marked as cancelled. So this is not just an USDC issue.

**Comment by eugene-mac** [comment]
@virus-zip there are no such problems anymore, since 1.3.5 version.
