### ISSUE TITLE
Orderbook - order of asks could be switched

### ISSUE THREAD

**Issue by virus-zip** [orionprotocol/trading-sdk#31]
In order to have a better experience, the orderbook for the ask prices could be switched in the following order:
smallest ask -> highest ask
highest bid -> smallest bid

The first element of each array then could be the current next price for the next trade. This would better the user experience a lot.

**Comment by eugene-mac** [comment]
> In order to have a better experience, the orderbook for the ask prices could be switched in the following order: smallest ask -> highest ask highest bid -> smallest bid
> 
> The first element of each array then could be the current next price for the next trade. This would better the user experience a lot.

@virus-zip A similar sorting implementation is coming soon
